os:
  - linux
  - osx
sudo: false
language: go
go:
  - 1.x
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# Don't email me the results of the test runs.
notifications:
  email: false

before_script:

script:
  - go test -v -race ./...  # Run all the tests with the race detector enabled
